# OPTUNA VERİLERİLERİNDEN DÖNEN VERİLER 
E01:
  seq_len: 1024
  lr_schedule: cosine
  learning_rate: 1.5e-5
  warmup_ratio: 0.035
  weight_decay: 0.05
  rope_scaling: null

  batch_size: 6
  grad_acc: 2
  num_epochs: 2

  eval_split_ratio: 0.01
  max_eval_samples: 2000
  eval_steps: 2000
  save_steps: 2000
  save_total_limit: 2
  logging_steps: 50
  seed: 42

# DAHA HIZLI EĞİTİM İÇİN
E01_fast:
  seq_len: 1024
  lr_schedule: cosine
  learning_rate: 1.5e-5
  warmup_ratio: 0.03
  weight_decay: 0.05
  rope_scaling: null

  batch_size: 6
  grad_acc: 2
  num_epochs: 2

  # 🔥 en büyük hız kazanımı burada
  eval_split_ratio: 0.005        # %1 → %0.5
  max_eval_samples: 1000         # 2000 → 1000
  eval_steps: 6000               # 2000 → 6000
  save_steps: 6000               # 2000 → 6000
  save_total_limit: 2
  logging_steps: 100
  seed: 42

# 18-24 SAAT EĞİTİM İÇİN (270 saat → ~20 saat)
E01_1day:
  seq_len: 768                   # 1024 → 768 (%25-30 hız kazanımı)
  lr_schedule: cosine
  learning_rate: 1.5e-5          # LR sabit tut (kalite korunur)
  warmup_ratio: 0.03
  weight_decay: 0.05
  rope_scaling: null

  batch_size: 8                  # 6 → 8 (H100 80GB yeterli)
  grad_acc: 2
  num_epochs: 1                  # 2 → 1 (×0.5 süre)
  max_steps: 40000               # Epoch yerine step-based (40K step ≈ 17 saat)

  eval_split_ratio: 0.005        # Küçük eval seti
  max_eval_samples: 1000
  eval_steps: 8000               # Daha az evaluation
  save_steps: 8000
  save_total_limit: 2
  logging_steps: 100
  seed: 42
